---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  # Binaries
  PYTHON_BIN: python3
  HUGO_BIN: hugo
  # Directories
  CONTENT_DIR: "{{.ROOT_DIR}}/content"
  POSTS_DIR: "{{.CONTENT_DIR}}/posts"

includes:
  hugo: .taskfiles/hugo/taskfile.yaml

dotenv: [".env"]

# env:
#   ENVVAR: ''

tasks:
  default: task -l

  catchup:
    desc: Catch feature branch up to main
    interactive: true
    cmds:
      - cmd: git stash # save any work-in-progress
      - defer: git stash pop # restore work-in-progress
      - cmd: git fetch origin main # update remote
      - task: _rebase
      - cmd: echo "git rebase successful"
      # - cmd: git push --force-with-lease
      - cmd: echo "Caught up with main!  To complete, use '\033[0;36mgit push --force-with-lease\033[0m'"

  push:
    desc: Push to Remote Origin
    interactive: true
    cmd: GIT_SSH_COMMAND='ssh -i /home/sepfy/.ssh/id_ed25519 -o IdentitiesOnly=yes' git push origin main

  _rebase:
    desc: Git rebase on main
    interactive: true
    # internal: true
    cmd: |
      git rebase origin/main --rebase-merges \
      || (echo "Merge conflicts detected, exiting task. Use 'git rebase --continue'." \
        && exit 1)